---
#yum --enablerepo=rhel-7-server-rhv-4.2-manager-rpms install python-ovirt-engine-sdk4
#ansible-playbook vm-snapshot-rhhi.yml
- name: snapshot vms
  hosts: localhost
  gather_facts: no
  vars:
    description_comment: "snap after gdeploy"
    server_list:
      - gluster-1
      - gluster-2
      - gluster-3
      - gluster-4
      - gluster-5
      - gluster-6
#      - gluster-client

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: https://rhvm.rnelson-demo.com/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: RedHat1!

    - name: perform snap
      ovirt_snapshots:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ item }}"
        description: "{{ description_comment }}"
        use_memory: true
      with_items:
       - "{{ server_list }}"
#       - gluster-1
#       - gluster-2
#       - gluster-3
#       - gluster-4
#       - gluster-5
#       - gluster-6
#       - gluster-client

    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
