---
#ansible-playbook -u root 1-prep.yml -k
- hosts: rhhi
  name: Prepare systems before installing RHHI
  gather_facts: yes
  vars:
    activation_key: rnelson-rhhi
    rhn_org_id: 1979710
    pool: 8a85f9833e1404a9013e3cddf95a0599

  tasks:
  - name: Copy /etc/hosts file
    copy:
      src: etc-hosts
      dest: /etc/hosts
      mode: 0644
    tags: pre

#  - name: Copy Ansible hosts file
#    copy:
#      src: ansible-hosts
#      dest: /etc/ansible/hosts
#      mode: 0644
#    tags: pre

  - name: ensure SSH key is generated
    command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
    args:
      creates: /root/.ssh/id_rsa
    when: ansible_nodename == "rhhi1.rnelson-demo.com"
    tags: keys

  - name: fetch RHHI-1 ssh key
    shell: cat ~/.ssh/id_rsa.pub
    register: ssh_keys
    when: ansible_nodename == "rhhi1.rnelson-demo.com"
    tags:
      - keys

  - name: verify key
    debug: msg="{{ ssh_keys.stdout }}"
    when: ansible_nodename == "rhhi1.rnelson-demo.com"
    tags:
      - keys

  - name: deploy keys on all servers
    authorized_key: user=root key="{{ item[0] }}"
    delegate_to: "{{ item[1] }}"
    with_nested:
      - "{{ ssh_keys.stdout }}"
      - "{{groups['rhhi']}}"
    when: ansible_nodename == "rhhi1.rnelson-demo.com"
    tags:
      - keys

  - name: Install personal SSH public key
    authorized_key:
      user: root
      key: "{{ lookup('file', 'rnelson-homelab.pub') }}"
    tags: keys

#  - name: Create known_hosts
#    lineinfile:
#      path: /root/.ssh/known_hosts
#      create: yes
#      state: present
#      line: "{{ lookup('pipe', 'ssh-keyscan -t ecdsa-sha2-nistp256 '+item) }}"
#    with_items:
#      - rhhi1.rnelson-demo.com
#      - rhhi2.rnelson-demo.com
#      - rhhi3.rnelson-demo.com
#      - 10.0.0.11
#      - 10.0.0.12
#      - 10.0.0.13
#      - rhhi1-gluster.rnelson-demo.com
#      - rhhi2-gluster.rnelson-demo.com
#      - rhhi3-gluster.rnelson-demo.com
#    delegate_to: rhhi1.rnelson-demo.com
#    run_once: true
#    tags: keys

  - name: Create known_hosts (task above preferred, but route table on VPN not working)
    shell: "ssh-keyscan -t ecdsa-sha2-nistp256 {{item}} >> /root/.ssh/known_hosts"
    with_items:
      - rhhi1.rnelson-demo.com
      - rhhi2.rnelson-demo.com
      - rhhi3.rnelson-demo.com
#      - 10.0.0.11
#      - 10.0.0.12
#      - 10.0.0.13
      - rhhi1-gluster.rnelson-demo.com
      - rhhi2-gluster.rnelson-demo.com
      - rhhi3-gluster.rnelson-demo.com
    delegate_to: rhhi1.rnelson-demo.com
    run_once: true
    tags: keys

  - name: Register
    command: subscription-manager register --activationkey={{activation_key}} --org={{rhn_org_id}}
    ignore_errors: yes #Added this because I'm using the Employee SKU, which doesn't match the auto-attach for RHV-H.
    tags: register

  - name: Attach
    command: subscription-manager attach --pool={{pool}}
    tags: register

  - name: Disable All and Enable Specific Repositories
    command: subscription-manager repos --disable="*" --enable=rhel-7-server-rhvh-4-rpms
    tags: register
