---
#ansible-playbook -u root 2-storage.yml
- hosts: rhhi1.rnelson-demo.com
  name: Deploy RHHI Storage

  tasks:
    - name: copy gdeploy.conf
      copy:
        src: files/gdeployConfig-working.conf
        dest: /tmp/gdeploy.conf
        owner: root
        group: root
        mode: 0600

    - name: configure gluster
      command: gdeploy -c /tmp/gdeploy.conf -vv --trace
      register: gdeploy_run

    - name: debug gdeploy.conf
      debug: msg="{{ gdeploy_run }}"
