---
#ansible-playbook 4-hosts-and-network.yml
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: https://{{rhvm_fqdn}}/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: RedHat1!

    - name: add hosts to cluster
      ovirt_hosts:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        name: "{{item}}"
        address: "{{item}}"
        password: "{{adminPassword}}"
        hosted_engine: deploy
      with_items:
        - {{node2-fqdn}}
        - {{node3-fqdn}}

    - name: sleep for 120 seconds and continue with play
      wait_for: timeout=120
      delegate_to: localhost

    - name: add gluster network
      ovirt_networks:
        auth: "{{ ovirt_auth }}"
        data_center: Default
        name: gluster
        vm_network: false
        clusters:
        - name: Default
          gluster: true
          migration: true
          required: false
        state: present

    - name: Add gluster network to eno2
      ovirt_host_networks:
        auth: "{{ ovirt_auth }}"
        name: "{{node1-fqdn}}"
        interface: eno2
        networks:
          - name: gluster
            boot_protocol: static
            address: "{{node1-gluster-ip}}"
            netmask: 255.255.255.0

    - name: Add gluster network to eno2
      ovirt_host_networks:
        auth: "{{ ovirt_auth }}"
        name: "{{node2-fqdn}}"
        interface: "{{node-If2}}"
        networks:
          - name: gluster
            boot_protocol: static
            address: "{{node2-gluster-ip}}"
            netmask: 255.255.255.0

    - name: Add gluster network to eno2
      ovirt_host_networks:
        auth: "{{ ovirt_auth }}"
        name: "{{node3-fqdn}}"
        interface: "{{node-If2}}"
        networks:
          - name: gluster
            boot_protocol: static
            address: "{{node3-gluster-ip}}"
            netmask: 255.255.255.0

    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
