---
#ansible-playbook 4-hosts.yml
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: https://rhvm.rnelson-demo.com/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: RedHat1!

    - ovirt_hosts:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        name: "{{item}}"
        address: "{{item}}"
        password: RedHat1!
        hosted_engine: deploy
      with_items:
        - rhhi2.rnelson-demo.com
        - rhhi3.rnelson-demo.com

    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
