---
- hosts: gluster
  gather_facts: no
  ignore_errors: yes

  tasks:
  - name: "Stop the Gluster volume"
    gluster_volume: name={{ item }} state=stopped
    run_once: yes
    with_items: [ ganesha ]

  - name: "Delete the Gluster volume"
    gluster_volume: name={{ item }} state=absent
    run_once: yes
    with_items: [ ganesha ]

  - name: "Remove brick_dirs"
    file: path=/gluster_bricks/{{ item }}/{{ item }}/ state=absent
    with_items: [ ganesha ]

  - name: "Unmount the bricks"
    mount: path=/gluster_bricks/{{ item }} state=absent
    with_items: [ ganesha ]

  - name: "Dissolve the Trusted Storage Pool"
    command: gluster peer detach {{ item }}
    with_items: [ gluster-1.rnelson-demo.com, gluster-2.rnelson-demo.com, gluster-3.rnelson-demo.com, gluster-4.rnelson-demo.com, gluster-5.rnelson-demo.com, gluster-6.rnelson-demo.com ]

  - name: "Remove the VGs"
    command: vgremove {{ item }} --force
    with_items: [ gluster_vg1 ]

  - name: "Remove the PVs"
    command: pvremove /dev/{{ item }} --force
    with_items: [ vdb, vdc ]

  - name: "Wipe the drives"
    command: wipefs -af /dev/{{ item }}
    with_items: [ vdb, vdc ]

  - name: "Clean disks the hard way"
    command: dd if=/dev/zero of=/dev/{{ item }} bs=1M count=10
    with_items: [ vdb, vdc ]

#  - name: "remove shared storage line in /etc/fstab"
#    lineinfile:
#      path: /etc/fstab
#      state: absent
#      regexp: ''
