#yum --enablerepo=rhel-7-server-rhv-4.2-manager-rpms install python-ovirt-engine-sdk4
#ansible-playbook -u root 1-gluster-deploy.yml -k
---
- hosts: localhost
  name: Create Gluster servers and client
  gather_facts: no

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: https://rhvm.rnelson-demo.com/ovirt-engine/api
        insecure: yes
        username: admin@internal
        password: RedHat1!

    - name: Create VMs
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        cluster: Default
        template: rhel-7.6-kvm
        storage_domain: vmstore
        name: "{{ item }}"
        state: running
        instance_type: Medium
        nics:
          - name: nic1
            profile_name: ovirtmgmt
        cloud_init:
          host_name: "{{ item }}.rnelson-demo.com"
          user_name: root
          root_password: RedHat1!
          authorized_ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmn8iPMGUA5Pf+5Rl+APPs0IGdFlmbSm04/bn2LXBIE3kF4tH/MvZdcJCQEKegC/bSicqEPz8BYFkNPNqqY52bVwIbneHIPraJDD8HhGiIY/A32mGjLr4rZ+FBo14Hy/rkq8WdmxbrrSX61zHEwHEC369jH43RzvICjdlAzHwO2+cnkteKCcRkAFrcSlgyrr0tt9HTUMVB7FPBFrqplxZGLuGlxdRSOA9vAupaJ44VBPtUA7hEaUyK9DQBWIKoBjdM/S/n8ySq3zCGeh6oeSXwD605VPDRSre5NWwvtO86eBOdT00WHtGhvalij4UX2s3zYN8DyRqxS3VHjKku0gCZ rnelson@laptop.rnelson-demo.com
          nic_name: eth0
          nic_on_boot: true
          nic_boot_protocol: dhcp

          custom_script: |
            runcmd:
              - hostnamectl set-hostname {{ item }}.rnelson-demo.com
              - yum -y remove cloud-init
        wait: true
      with_items:
         - gluster-1-fips
         - gluster-2-fips
         - gluster-3-fips
         - gluster-client-fips

    - name: Create and attach disks for gluster nodes
      ovirt_disk:
        auth: "{{ ovirt_auth }}"
        vm_name: "{{ item.vm_name }}"
        storage_domain: "nfs-synology"
        name: "{{ item.name }}-{{ item.id }}"
        size: "{{ item.size }}"
        format: cow
        interface: virtio
        wait: true
      with_items:
        - { vm_name: 'gluster-1-fips', name: 'data-disk', id: '1', size: '15GiB' }
        - { vm_name: 'gluster-2-fips', name: 'data-disk', id: '1', size: '15GiB' }
        - { vm_name: 'gluster-3-fips', name: 'data-disk', id: '1', size: '15GiB' }


    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent

- hosts: gluster-server-fips
  name: Initial Setup for Gluster Nodes
  vars:
      activation_key: rnelson-rhhi
      rhn_org_id: 1979710
      pool: 8a85f9833e1404a9013e3cddf95a0599
      repos:
      repo_list:
        - rhel-7-server-rpms
        - rhel-7-server-ansible-2-rpms
        - rh-gluster-3-for-rhel-7-server-rpms


  tasks:
    - name: Register to RHN and attach SKU through Activation Key
      redhat_subscription:
        state: present
        activationkey: "{{ activation_key }}"
        org_id: "{{ rhn_org_id }}"

    - name: Disable All and Enable Specific Repositories
      block:
      - set_fact:
          repos: "{{ repo_list | join(' --enable=') }}"
      - debug:
          var: repos
      - name: Enable repos for RHEL7
        command: subscription-manager repos --disable="*" --enable={{ repos }}
      tags: register

    - name: Install RPMs
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - redhat-storage-server
        - gstatus
        - ansible
        - gdeploy

    - name: Update
      yum:
        name: "*"
        state: latest

    - name: Start and Enable firewalld
      systemd: name=firewalld state=started enabled=yes

    - name: Configure firewalld
      firewalld:
        service: glusterfs
        permanent: true
        immediate: yes
        state: enabled

    - name: Reboot
      shell: sleep 10 && /sbin/shutdown -r now
      async: 300
      poll: 0

- hosts: gluster-client-fips
  name: configure gluster-client
  vars:
      activation_key: rnelson-rhhi
      rhn_org_id: 1979710
      pool: 8a85f9833e1404a9013e3cddf95a0599
      repos:
      repo_list:
        - rhel-7-server-rpms
        - rh-gluster-3-for-rhel-7-server-rpms

  tasks:
    - name: Register to RHN and attach SKU through Activation Key
      redhat_subscription:
        state: present
        activationkey: "{{ activation_key }}"
        org_id: "{{ rhn_org_id }}"

    - name: Disable All and Enable Specific Repositories
      block:
      - set_fact:
          repos: "{{ repo_list | join(' --enable=') }}"
      - debug:
          var: repos
      - name: Enable repos for RHEL7
        command: subscription-manager repos --disable="*" --enable={{ repos }}
      tags: register

    - name: Install RPMs
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - glusterfs-fuse

    - name: Update
      yum:
        name: "*"
        state: latest

    - name: Start and Enable firewalld
      systemd: name=firewalld state=started enabled=yes

    - name: Configure firewalld
      firewalld:
        service: glusterfs
        permanent: true
        immediate: yes
        state: enabled

    - name: Reboot
      shell: sleep 10 && /sbin/shutdown -r now
      async: 300
      poll: 0

- hosts: gluster-1.rnelson-demo.com
  name: configure ssh keys on gluster-1

  tasks:
    - name: ensure SSH key is generated
      command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
      args:
        creates: /root/.ssh/id_rsa

    - name: Create known_hosts
      shell: "ssh-keyscan -t ecdsa-sha2-nistp256 {{item}} >> /root/.ssh/known_hosts"
      with_items:
        - gluster-1-fips.rnelson-demo.com
        - gluster-2-fips.rnelson-demo.com
        - gluster-3-fips.rnelson-demo.com
        - gluster-client-fips.rnelson-demo.com
