---
#This playbook is expected to run from laptop.
# ansible-playbook -u root 1-bastion-prep.yml -k
# need to add git to download rickmanley-lab github.
- hosts: bastion
  name: Prepare Bastion host for OCP/OCS Install
  gather_facts: yes
  vars:
    activation_key: rnelson-rhhi
    rhn_org_id: 1979710
    pool: 8a85f9833e1404a9013e3cddf95a0599
    repos:
    repo_list:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-ose-3.11-rpms
      - rhel-7-server-ansible-2.6-rpms
      - rhel-7-server-rhv-4.2-manager-rpms # contains ovirt-ansible-roles, python-ovirt-engine-sdk4

  tasks:
  - name: Copy /etc/hosts file
    copy:
      src: etc-hosts
      dest: /etc/hosts
      mode: 0644
    tags: pre

  - name: ensure SSH key is generated
    command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
    args:
      creates: /root/.ssh/id_rsa

  - name: Install SSH public key
    authorized_key:
      user: root
      key: "{{ lookup('file', 'rnelson-homelab.pub') }}"
    tags: keys

  - name: Register
    command: subscription-manager register --activationkey={{activation_key}} --org={{rhn_org_id}}
    ignore_errors: yes #Added this because I'm using the Employee SKU, and the auto attach may fail
    tags: register

  - name: Disable All and Enable Specific Repositories
    block:
    - set_fact:
        repos: "{{ repo_list | join(' --enable=') }}"
    - debug:
        var: repos
    - name: Enable repos for RHEL7
      command: subscription-manager repos --disable="*" --enable={{ repos }}
    tags: register

  - name: Install misc packages
    package:
      name: screen,bind-utils,vim-enhanced,libselinux-python,ansible,git,python-ovirt-engine-sdk4,ovirt-ansible-roles
      state: present
    tags: rpms

  - name: Copy Ansible hosts file
    copy:
      src: ansible-hosts
      dest: /etc/ansible/hosts
      mode: 0644
    tags: pre

  - name: Copy ansible.cfg file
    copy:
      src: ansible.cfg
      dest: /etc/ansible/ansible.cfg
      mode: 0644
    tags: pre
