---
#Using the parted module won't work for /dev/sda which already has boot, swap and root mounted.
- name: Create engine partition (this is a workaround. better in post of kickstart?)
  shell: echo -e "n\n\n\n+80G\nw\n" | fdisk /dev/sda
  args:
    executable: /bin/bash
  ignore_errors: yes
  tags: disk-prep

- name: Create ssdvmstore partition (this is a workaround. better in post of kickstart?)
  shell: echo -e "n\n\n\n\nw\n" | fdisk /dev/sda
  args:
    executable: /bin/bash
  ignore_errors: yes
  tags: disk-prep

- name: partprobe
  command: partprobe
  tags: disk-prep
